# 基于决策树的白酒质量预测

In [12]:
import numpy as np
from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

In [7]:
file_path = './data/wine.txt'

X, y = [], []
with open(file_path, 'r') as f:
    for line in f.readlines():
        data = [float(x) for x in line.split(',')]
        X.append(data[1:])
        y.append(data[0])
X, y = np.array(X), np.array(y)
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

### Two groups

In [10]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.25, random_state=5)
cf_dt = DecisionTreeClassifier()
cf_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [11]:
y_test_pred = cf_dt.predict(X_test)

acc = 100 * (y_test == y_test_pred).sum() / X_test.shape[0]
print('精度为', acc, '%')

精度为 91.11111111111111 %


### Confusion matrics 混淆矩阵

In [13]:
confusion_mat = confusion_matrix(y_test, y_test_pred)
print(confusion_mat)

[[17  2  0]
 [ 1 12  1]
 [ 0  0 12]]
